import type { FormStep } from '../../schema/types';

export const schema: FormStep[] = [
  {
    id: 'welcome',
    type: 'welcome',
    title: "Let's get you onboarded.",
    subtitle: "We'll walk you through a few quick steps — your details, home info, and bank account.",
    meta: {
      overline: 'Homeowner Onboarding',
      ctaLabel: 'Get Started',
      estimatedTime: '~8 min',
      audience: 'landlord',
      successTitle: "We've got everything we need.",
      successSubtitle: 'Your property specialist will be in touch shortly.',
    },
  },
  {
    id: 'basic-info',
    type: 'info-screen',
    title: 'Basic details',
    subtitle: "Let's start with your name and contact info.",
  },
  {
    id: 'contact',
    type: 'field-group',
    title: 'Your details',
    fields: [
      { name: 'firstName', type: 'text', label: 'First name', required: true },
      { name: 'lastName', type: 'text', label: 'Last name', required: true },
      { name: 'email', type: 'email', label: 'Email', required: true },
    ],
  },
  {
    id: 'aadhaar-front',
    type: 'file-upload',
    title: 'Upload Aadhaar card (front)',
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'Aadhaar front' },
    meta: { fieldName: 'aadhaarFront' },
  },
  {
    id: 'aadhaar-back',
    type: 'file-upload',
    title: 'Upload Aadhaar card (back)',
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'Aadhaar back' },
    meta: { fieldName: 'aadhaarBack' },
  },
  {
    id: 'pan-upload',
    type: 'file-upload',
    title: 'Upload PAN card',
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'PAN card' },
    meta: { fieldName: 'panUpload' },
  },
  {
    id: 'permanent-address',
    type: 'long-text',
    title: 'Permanent address',
    meta: { fieldName: 'permanentAddress' },
    validation: [{ type: 'required', message: 'Permanent address is required' }],
  },
  {
    id: 'phone',
    type: 'phone',
    title: 'Contact phone number',
    meta: { fieldName: 'phone' },
    validation: [{ type: 'required', message: 'Phone number is required' }],
  },
  {
    id: 'home-info',
    type: 'info-screen',
    title: 'Now for the home details',
    subtitle: "Tell us about the home we'll be managing.",
  },
  {
    id: 'unit-number',
    type: 'text-input',
    title: 'House / apartment number',
    meta: { fieldName: 'unitNumber' },
    validation: [{ type: 'required', message: 'Unit number is required' }],
  },
  {
    id: 'postal-address',
    type: 'long-text',
    title: 'Postal address of the home',
    meta: { fieldName: 'postalAddress' },
    validation: [{ type: 'required', message: 'Postal address is required' }],
  },
  {
    id: 'security-contact',
    type: 'phone',
    title: 'Security guard / building manager contact',
    meta: { fieldName: 'securityContact' },
    validation: [{ type: 'required', message: 'This contact is required' }],
  },
  {
    id: 'movein-charges',
    type: 'text-input',
    title: 'Building / society move-in charges',
    meta: { fieldName: 'moveinCharges' },
    validation: [{ type: 'required', message: 'Move-in charges are required' }],
  },
  {
    id: 'power-backup',
    type: 'yes-no',
    title: 'Does the home have power backup?',
    meta: { fieldName: 'powerBackup' },
    validation: [{ type: 'required', message: 'Please select an option' }],
  },
  {
    id: 'bescom-access',
    type: 'single-select',
    title: 'How do you access your BESCOM account?',
    options: [
      { label: 'BESCOM Account', value: 'BESCOM Account' },
      { label: 'Physical Bill', value: 'Physical Bill' },
    ],
    meta: { fieldName: 'bescomAccess' },
  },
  {
    id: 'bescom-account-id',
    type: 'text-input',
    title: 'BESCOM account ID',
    condition: { field: 'bescomAccess', operator: 'eq', value: 'BESCOM Account' },
    meta: { fieldName: 'bescomAccountId' },
  },
  {
    id: 'bescom-password',
    type: 'text-input',
    title: 'BESCOM password',
    condition: { field: 'bescomAccess', operator: 'eq', value: 'BESCOM Account' },
    meta: { fieldName: 'bescomPassword' },
  },
  {
    id: 'electricity-bill',
    type: 'file-upload',
    title: 'Upload a recent electricity bill',
    condition: { field: 'bescomAccess', operator: 'eq', value: 'Physical Bill' },
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'Electricity bill' },
    meta: { fieldName: 'electricityBill' },
  },
  {
    id: 'lpg-type',
    type: 'single-select',
    title: 'What type of gas connection does the home have?',
    options: [
      { label: 'LPG Cylinder', value: 'LPG Cylinder' },
      { label: 'Gas Pipeline', value: 'Gas Pipeline' },
      { label: 'None', value: 'None' },
    ],
    meta: { fieldName: 'lpgType' },
  },
  {
    id: 'gas-provider',
    type: 'text-input',
    title: 'Gas pipeline provider name',
    condition: { field: 'lpgType', operator: 'eq', value: 'Gas Pipeline' },
    meta: { fieldName: 'gasProvider' },
  },
  {
    id: 'gas-account',
    type: 'text-input',
    title: 'Gas pipeline account number',
    condition: { field: 'lpgType', operator: 'eq', value: 'Gas Pipeline' },
    meta: { fieldName: 'gasAccount' },
  },
  {
    id: 'lpg-vendor-phone',
    type: 'phone',
    title: 'LPG cylinder vendor phone number',
    condition: { field: 'lpgType', operator: 'eq', value: 'LPG Cylinder' },
    meta: { fieldName: 'lpgVendorPhone' },
  },
  {
    id: 'bank-info',
    type: 'info-screen',
    title: 'Moving on to the most important part',
    subtitle: "Your bank details — so we can transfer your rental income on time, every time.",
  },
  {
    id: 'bank-details',
    type: 'field-group',
    title: 'Bank account details',
    fields: [
      { name: 'beneficiaryName', type: 'text', label: 'Beneficiary name', required: true },
      { name: 'accountNumber', type: 'text', label: 'Account number', required: true },
      { name: 'ifscCode', type: 'text', label: 'IFSC code', required: true },
    ],
  },
  {
    id: 'house-rules',
    type: 'long-text',
    title: 'Any house rules or special instructions?',
    subtitle: 'Optional — anything you want your tenant to know.',
    meta: { fieldName: 'houseRules' },
  },
];
