import type { FormStep } from './types';

export const onboardingSchema: FormStep[] = [
  {
    id: 'welcome',
    type: 'welcome',
    title: 'Welcome aboard, homeowners!',
    subtitle: 'This form will help us capture your property details, PAN / Aadhaar and bank account details to process the security deposit and rent.',
    meta: {
      estimatedTime: '10-15 minutes',
      documentsRequired: [
        'Aadhaar Card of Owner',
        'PAN Card of Owner',
        'Bank Account Details',
        'Property Verification Documents',
      ],
    },
  },
  {
    id: 'role-selection',
    type: 'single-select',
    title: 'Select the option that best describes your role',
    options: [
      { label: 'Owner', value: 'owner', description: 'Person whose name is on property documents', icon: '🏠' },
      { label: 'Point of Contact', value: 'poc', description: 'Receives updates and communicates with platform', icon: '📋' },
      { label: 'Both Owner and POC', value: 'both', description: 'You handle both roles', icon: '🤝' },
    ],
    nextOverride: { poc: 'poc-details' },
  },
  {
    id: 'homeowner-count',
    type: 'number-picker',
    title: 'How many homeowners are there for this property?',
    subtitle: 'We\'ll collect details for each homeowner separately.',
    condition: { field: 'role', operator: 'neq', value: 'poc' },
    fields: [
      {
        name: 'homeownerCount',
        type: 'number',
        label: 'Number of homeowners',
        validation: [
          { type: 'min', params: { min: 1 }, message: 'At least 1 homeowner is required' },
          { type: 'max', params: { max: 10 }, message: 'Maximum 10 homeowners allowed' },
        ],
      },
    ],
  },
  {
    id: 'homeowner-details',
    type: 'field-group',
    title: 'Homeowner details',
    subtitle: 'Please provide the personal details',
    condition: { field: 'role', operator: 'neq', value: 'poc' },
    repeatable: { countField: 'homeownerCount', itemLabel: 'Homeowner', dataArrayField: 'homeowners' },
    fields: [
      { name: 'firstName', type: 'text', label: 'First Name', placeholder: 'Enter first name', required: true, validation: [{ type: 'required', message: 'First name is required' }] },
      { name: 'lastName', type: 'text', label: 'Last Name', placeholder: 'Enter last name', required: true, validation: [{ type: 'required', message: 'Last name is required' }] },
      { name: 'phone', type: 'tel', label: 'Phone Number', placeholder: 'Enter phone number', required: true, validation: [{ type: 'phone', message: 'Enter a valid 10-digit phone number' }] },
      { name: 'email', type: 'email', label: 'Email Address', placeholder: 'Enter email address', required: true, validation: [{ type: 'email', message: 'Enter a valid email address' }] },
    ],
  },
  {
    id: 'aadhaar-front',
    type: 'file-upload',
    title: 'Upload Aadhaar Card (Front)',
    subtitle: 'We\'ll extract your details automatically to save time.',
    condition: { field: 'role', operator: 'neq', value: 'poc' },
    repeatable: { countField: 'homeownerCount', itemLabel: 'Homeowner', dataArrayField: 'homeowners' },
    fileUpload: {
      accept: ['.jpg', '.jpeg', '.png', '.pdf'],
      maxSizeMB: 10,
      label: 'Aadhaar Card — Front Side',
      description: 'Upload a clear photo or scan of the front of your Aadhaar card',
      ocrEnabled: true,
    },
  },
  {
    id: 'aadhaar-back',
    type: 'file-upload',
    title: 'Upload Aadhaar Card (Back)',
    subtitle: 'This helps us verify your address details.',
    condition: { field: 'role', operator: 'neq', value: 'poc' },
    repeatable: { countField: 'homeownerCount', itemLabel: 'Homeowner', dataArrayField: 'homeowners' },
    fileUpload: {
      accept: ['.jpg', '.jpeg', '.png', '.pdf'],
      maxSizeMB: 10,
      label: 'Aadhaar Card — Back Side',
      description: 'Upload a clear photo or scan of the back of your Aadhaar card',
      ocrEnabled: true,
    },
  },
  {
    id: 'pan-input',
    type: 'text-input',
    title: 'Enter PAN Number',
    subtitle: 'We\'ll verify your PAN details in real-time.',
    condition: { field: 'role', operator: 'neq', value: 'poc' },
    repeatable: { countField: 'homeownerCount', itemLabel: 'Homeowner', dataArrayField: 'homeowners' },
    fields: [
      {
        name: 'pan',
        type: 'text',
        label: 'PAN Number',
        placeholder: 'e.g. ABCDE1234F',
        required: true,
        validation: [{ type: 'pan', message: 'Enter a valid PAN (e.g. ABCDE1234F)' }],
      },
    ],
    asyncValidation: 'verify-pan',
  },
  {
    id: 'pan-upload',
    type: 'file-upload',
    title: 'Upload PAN Card',
    subtitle: 'Upload a clear photo or scan of your PAN card.',
    condition: { field: 'role', operator: 'neq', value: 'poc' },
    repeatable: { countField: 'homeownerCount', itemLabel: 'Homeowner', dataArrayField: 'homeowners' },
    fileUpload: {
      accept: ['.jpg', '.jpeg', '.png', '.pdf'],
      maxSizeMB: 10,
      label: 'PAN Card',
      description: 'We\'ll verify this against the PAN number you provided',
      ocrEnabled: false,
    },
  },
  {
    id: 'property-document',
    type: 'file-upload',
    title: 'Upload Property Verification Document',
    subtitle: 'Upload one of: Sale deed, Property tax receipt, Registration document, or Electricity bill.',
    condition: { field: 'role', operator: 'neq', value: 'poc' },
    fileUpload: {
      accept: ['.jpg', '.jpeg', '.png', '.pdf'],
      maxSizeMB: 10,
      label: 'Property Document',
      description: 'This must contain the owner\'s name and property address',
      ocrEnabled: false,
    },
  },
  {
    id: 'bank-intro',
    type: 'info-screen',
    title: 'Bank Account Details',
    subtitle: 'Now let\'s capture bank account details for rent payments. Please keep your bank details handy.',
    condition: { field: 'role', operator: 'neq', value: 'poc' },
    meta: { icon: '🏦' },
  },
  {
    id: 'bank-count',
    type: 'number-picker',
    title: 'How many bank accounts do you want to add?',
    subtitle: 'You can add up to 5 bank accounts for rent distribution.',
    condition: { field: 'role', operator: 'neq', value: 'poc' },
    fields: [
      {
        name: 'bankAccountCount',
        type: 'number',
        label: 'Number of bank accounts',
        validation: [
          { type: 'min', params: { min: 1 }, message: 'At least 1 bank account is required' },
          { type: 'max', params: { max: 5 }, message: 'Maximum 5 bank accounts allowed' },
        ],
      },
    ],
  },
  {
    id: 'bank-details',
    type: 'field-group',
    title: 'Bank Account Details',
    subtitle: 'Enter the account details for rent payments',
    condition: { field: 'role', operator: 'neq', value: 'poc' },
    repeatable: { countField: 'bankAccountCount', itemLabel: 'Bank Account', dataArrayField: 'bankAccounts' },
    fields: [
      { name: 'beneficiaryName', type: 'text', label: 'Beneficiary Name', placeholder: 'Name as per bank records', required: true, validation: [{ type: 'required', message: 'Beneficiary name is required' }] },
      { name: 'accountNumber', type: 'text', label: 'Account Number', placeholder: 'Enter account number', required: true, validation: [{ type: 'minLength', params: { min: 9 }, message: 'Account number must be at least 9 digits' }] },
      { name: 'confirmAccountNumber', type: 'text', label: 'Confirm Account Number', placeholder: 'Re-enter account number', required: true, validation: [{ type: 'match', params: { field: 'accountNumber' }, message: 'Account numbers do not match' }] },
      { name: 'ifscCode', type: 'text', label: 'IFSC Code', placeholder: 'e.g. HDFC0001234', required: true, validation: [{ type: 'ifsc', message: 'Enter a valid IFSC code' }] },
      { name: 'bankName', type: 'text', label: 'Bank Name', placeholder: 'Auto-filled from IFSC', required: true },
      { name: 'branchName', type: 'text', label: 'Branch Name', placeholder: 'Auto-filled from IFSC' },
    ],
    asyncValidation: 'verify-bank',
  },
  {
    id: 'poc-details',
    type: 'field-group',
    title: 'Point of Contact Details',
    subtitle: 'This person will receive updates and communications from us.',
    condition: { field: 'role', operator: 'neq', value: 'owner' },
    fields: [
      { name: 'poc.firstName', type: 'text', label: 'First Name', placeholder: 'Enter first name', required: true, validation: [{ type: 'required', message: 'First name is required' }] },
      { name: 'poc.lastName', type: 'text', label: 'Last Name', placeholder: 'Enter last name', required: true, validation: [{ type: 'required', message: 'Last name is required' }] },
      { name: 'poc.phone', type: 'tel', label: 'Phone Number', placeholder: 'Enter phone number', required: true, validation: [{ type: 'phone', message: 'Enter a valid 10-digit phone number' }] },
      { name: 'poc.email', type: 'email', label: 'Email Address', placeholder: 'Enter email address', required: true, validation: [{ type: 'email', message: 'Enter a valid email address' }] },
    ],
  },
  {
    id: 'backup-contact',
    type: 'field-group',
    title: 'Backup Contact (Optional)',
    subtitle: 'Add a backup contact in case we can\'t reach the primary contact.',
    fields: [
      { name: 'backupContact.firstName', type: 'text', label: 'First Name', placeholder: 'Enter first name' },
      { name: 'backupContact.lastName', type: 'text', label: 'Last Name', placeholder: 'Enter last name' },
      { name: 'backupContact.phone', type: 'tel', label: 'Phone Number', placeholder: 'Enter phone number' },
      { name: 'backupContact.email', type: 'email', label: 'Email Address', placeholder: 'Enter email address' },
    ],
  },
  {
    id: 'review',
    type: 'review',
    title: 'Review Your Details',
    subtitle: 'Please review all information before submitting. You can go back to edit any section.',
  },
];
