import type { FormStep } from '../../schema/types';

export const schema: FormStep[] = [
  {
    id: 'welcome',
    type: 'welcome',
    title: 'Property Information Capture',
    subtitle: 'Capture all property and society details for the ops team.',
    meta: {
      overline: 'Property Intel',
      estimatedTime: '~10 min',
      audience: 'internal',
      successTitle: 'Property information recorded.',
      successSubtitle: 'The operations team can now proceed.',
    },
  },
  {
    id: 'property-id',
    type: 'text-input',
    title: 'Property ID',
    meta: { fieldName: 'propertyId' },
    fields: [
      {
        name: 'propertyId',
        type: 'text',
        label: 'Property ID',
        placeholder: 'Enter property ID',
        required: true,
        validation: [{ type: 'required', message: 'Property ID is required' }],
      },
    ],
  },
  {
    id: 'configuration',
    type: 'single-select',
    title: 'Configuration',
    options: [
      { label: '1 BHK', value: '1bhk' },
      { label: '2 BHK', value: '2bhk' },
      { label: '3 BHK', value: '3bhk' },
      { label: '4 BHK', value: '4bhk' },
      { label: 'Studio', value: 'studio' },
    ],
    meta: { fieldName: 'configuration' },
  },
  {
    id: 'unit-type',
    type: 'text-input',
    title: 'Unit type',
    meta: { fieldName: 'unitType' },
    fields: [
      {
        name: 'unitType',
        type: 'text',
        label: 'Unit Type',
        placeholder: 'e.g. 2BHK-A, Studio-B',
      },
    ],
  },
  {
    id: 'google-maps-link',
    type: 'text-input',
    title: 'Google Maps link',
    meta: { fieldName: 'googleMapsLink' },
    fields: [
      {
        name: 'googleMapsLink',
        type: 'text',
        label: 'Google Maps Link',
        placeholder: 'Paste the Google Maps URL',
      },
    ],
  },
  {
    id: 'has-dedicated-parking',
    type: 'yes-no',
    title: 'Dedicated parking?',
    meta: { fieldName: 'hasDedicatedParking' },
  },
  {
    id: 'parking-description',
    type: 'text-input',
    title: 'Parking description',
    condition: { field: 'hasDedicatedParking', operator: 'eq', value: 'yes' },
    meta: { fieldName: 'parkingDescription' },
    fields: [
      {
        name: 'parkingDescription',
        type: 'text',
        label: 'Parking Description',
        placeholder: 'Describe the parking arrangement',
      },
    ],
  },
  {
    id: 'society-type',
    type: 'single-select',
    title: 'Society/villa type',
    options: [
      { label: 'Gated Society', value: 'gated_society' },
      { label: 'Standalone Building', value: 'standalone_building' },
      { label: 'Villa Community', value: 'villa_community' },
      { label: 'Independent', value: 'independent' },
    ],
    meta: { fieldName: 'societyType' },
  },
  {
    id: 'society-name',
    type: 'text-input',
    title: 'Society/building name',
    meta: { fieldName: 'societyName' },
    fields: [
      {
        name: 'societyName',
        type: 'text',
        label: 'Society/Building Name',
        placeholder: 'Enter society or building name',
      },
    ],
  },
  {
    id: 'has-lift',
    type: 'yes-no',
    title: 'Lift available?',
    meta: { fieldName: 'hasLift' },
  },
  {
    id: 'society-app',
    type: 'single-select',
    title: 'Society management app',
    options: [
      { label: 'MyGate', value: 'mygate' },
      { label: 'NoBroker', value: 'nobroker' },
      { label: 'Apartment Adda', value: 'apartment_adda' },
      { label: 'JEEVES', value: 'jeeves' },
      { label: 'Other', value: 'other' },
      { label: 'None', value: 'none' },
    ],
    meta: { fieldName: 'societyApp' },
  },
  {
    id: 'app-portal-name',
    type: 'text-input',
    title: 'App/portal name',
    condition: { field: 'societyApp', operator: 'eq', value: 'other' },
    meta: { fieldName: 'appPortalName' },
    fields: [
      {
        name: 'appPortalName',
        type: 'text',
        label: 'App/Portal Name',
        placeholder: 'Enter app or portal name',
      },
    ],
  },
  {
    id: 'manager-phone',
    type: 'phone',
    title: 'Society manager phone',
    meta: { fieldName: 'managerPhone' },
  },
  {
    id: 'security-phone',
    type: 'phone',
    title: 'Security phone',
    meta: { fieldName: 'securityPhone' },
  },
  {
    id: 'move-in-charges',
    type: 'text-input',
    title: 'Move-in charges',
    meta: { fieldName: 'moveInCharges' },
    fields: [
      {
        name: 'moveInCharges',
        type: 'number',
        label: 'Move-in Charges',
        placeholder: 'Enter amount in INR',
      },
    ],
  },
  {
    id: 'move-out-charges',
    type: 'text-input',
    title: 'Move-out charges',
    meta: { fieldName: 'moveOutCharges' },
    fields: [
      {
        name: 'moveOutCharges',
        type: 'number',
        label: 'Move-out Charges',
        placeholder: 'Enter amount in INR',
      },
    ],
  },
  {
    id: 'move-in-policy',
    type: 'long-text',
    title: 'Move-in policy',
    meta: { fieldName: 'moveInPolicy' },
  },
  {
    id: 'move-out-policy',
    type: 'long-text',
    title: 'Move-out policy',
    meta: { fieldName: 'moveOutPolicy' },
  },
  {
    id: 'society-email',
    type: 'text-input',
    title: 'Society email',
    meta: { fieldName: 'societyEmail' },
    fields: [
      {
        name: 'societyEmail',
        type: 'email',
        label: 'Society Email',
        placeholder: 'Enter society email address',
      },
    ],
  },
  {
    id: 'amenities',
    type: 'multi-select',
    title: 'Amenities',
    options: [
      { label: 'Swimming Pool', value: 'swimming_pool' },
      { label: 'Gym', value: 'gym' },
      { label: 'Clubhouse', value: 'clubhouse' },
      { label: 'Park/Garden', value: 'park_garden' },
      { label: 'Power Backup', value: 'power_backup' },
      { label: 'Security', value: 'security' },
      { label: 'CCTV', value: 'cctv' },
      { label: 'Intercom', value: 'intercom' },
      { label: 'Lift', value: 'lift' },
      { label: 'Covered Parking', value: 'covered_parking' },
      { label: 'Visitor Parking', value: 'visitor_parking' },
      { label: 'EV Charging', value: 'ev_charging' },
      { label: 'Indoor Games', value: 'indoor_games' },
      { label: 'Terrace Access', value: 'terrace_access' },
    ],
    meta: { fieldName: 'amenities' },
  },
  {
    id: 'society-rules-document',
    type: 'file-upload',
    title: 'Society rules document',
    fileUpload: {
      accept: ['.pdf'],
      maxSizeMB: 10,
      label: 'Upload society rules',
    },
    meta: { fieldName: 'societyRulesDocument' },
  },
  {
    id: 'garbage-schedule',
    type: 'text-input',
    title: 'Garbage collection schedule',
    meta: { fieldName: 'garbageSchedule' },
    fields: [
      {
        name: 'garbageSchedule',
        type: 'text',
        label: 'Garbage Collection Schedule',
        placeholder: 'e.g. Daily 7-9 AM',
      },
    ],
  },
  {
    id: 'separate-water-bill',
    type: 'yes-no',
    title: 'Separate water bill?',
    meta: { fieldName: 'separateWaterBill' },
  },
  {
    id: 'flent-pays-maintenance',
    type: 'yes-no',
    title: 'Flent pays maintenance?',
    meta: { fieldName: 'flentPaysMaintenance' },
  },
  {
    id: 'maintenance-amount',
    type: 'text-input',
    title: 'Monthly maintenance amount',
    condition: { field: 'flentPaysMaintenance', operator: 'eq', value: 'yes' },
    meta: { fieldName: 'maintenanceAmount' },
    fields: [
      {
        name: 'maintenanceAmount',
        type: 'number',
        label: 'Monthly Maintenance Amount',
        placeholder: 'Enter amount in INR',
      },
    ],
  },
  {
    id: 'maintenance-payment-details',
    type: 'field-group',
    title: 'Maintenance payment details',
    condition: { field: 'flentPaysMaintenance', operator: 'eq', value: 'yes' },
    fields: [
      {
        name: 'maintenanceAccountHolder',
        type: 'text',
        label: 'Account Holder Name',
        placeholder: 'Enter account holder name',
        required: true,
        validation: [
          { type: 'required', message: 'Account holder name is required' },
        ],
      },
      {
        name: 'maintenanceAccountNumber',
        type: 'text',
        label: 'Account Number',
        placeholder: 'Enter account number',
        required: true,
        validation: [
          { type: 'required', message: 'Account number is required' },
        ],
      },
      {
        name: 'maintenanceIfsc',
        type: 'text',
        label: 'IFSC Code',
        placeholder: 'Enter IFSC code',
        required: true,
        validation: [
          { type: 'ifsc', message: 'Enter a valid IFSC code' },
        ],
      },
      {
        name: 'maintenanceDueDate',
        type: 'number',
        label: 'Due Date',
        placeholder: 'Day of the month (1-31)',
      },
    ],
  },
  {
    id: 'maintenance-payment-cycle',
    type: 'single-select',
    title: 'Maintenance payment cycle',
    condition: { field: 'flentPaysMaintenance', operator: 'eq', value: 'yes' },
    options: [
      { label: 'Monthly', value: 'monthly' },
      { label: 'Quarterly', value: 'quarterly' },
      { label: 'Half-yearly', value: 'half_yearly' },
      { label: 'Annually', value: 'annually' },
    ],
    meta: { fieldName: 'maintenancePaymentCycle' },
  },
];
