import type { FormStep } from '../../schema/types';

export const schema: FormStep[] = [
  {
    id: 'your-name',
    type: 'text-input',
    title: 'Your name',
    meta: {
      fieldName: 'yourName',
      audience: 'internal',
      successTitle: 'Lead captured.',
      successSubtitle: 'The supply team will review and follow up.',
    },
  },
  {
    id: 'property-name',
    type: 'text-input',
    title: 'Property name',
    meta: { fieldName: 'propertyName' },
  },
  {
    id: 'property-type',
    type: 'dropdown',
    title: 'Property type',
    options: [
      { label: 'Independent House', value: 'Independent House' },
      { label: 'Gated Apartment', value: 'Gated Apartment' },
      { label: 'Non Gated Apartment', value: 'Non Gated Apartment' },
      { label: 'Gated Society', value: 'Gated Society' },
    ],
    meta: { fieldName: 'propertyType' },
  },
  {
    id: 'maps-link',
    type: 'text-input',
    title: 'Google Maps link',
    meta: { fieldName: 'mapsLink' },
  },
  {
    id: 'bhk-config',
    type: 'multi-select',
    title: 'BHK + bathrooms available',
    options: [
      { label: '1BHK + 1 Bath', value: '1bhk_1bath' },
      { label: '2BHK + 1 Bath', value: '2bhk_1bath' },
      { label: '2BHK + 2 Bath', value: '2bhk_2bath' },
      { label: '3BHK + 2 Bath', value: '3bhk_2bath' },
      { label: '3BHK + 3 Bath', value: '3bhk_3bath' },
      { label: '4BHK + 3 Bath', value: '4bhk_3bath' },
      { label: '4BHK + 4 Bath', value: '4bhk_4bath' },
    ],
    meta: { fieldName: 'bhkConfig' },
  },
  {
    id: 'poc-name',
    type: 'text-input',
    title: 'POC name',
    meta: { fieldName: 'pocName' },
  },
  {
    id: 'poc-type',
    type: 'dropdown',
    title: 'POC type',
    options: [
      { label: 'Security Guard', value: 'Security Guard' },
      { label: 'Society Manager', value: 'Society Manager' },
      { label: 'Broker', value: 'Broker' },
      { label: 'Resident', value: 'Resident' },
      { label: 'Other', value: 'Other' },
    ],
    meta: { fieldName: 'pocType' },
  },
  {
    id: 'poc-phone',
    type: 'phone',
    title: 'POC phone',
    meta: { fieldName: 'pocPhone' },
  },
  {
    id: 'landlord-name',
    type: 'text-input',
    title: 'Landlord name',
    meta: { fieldName: 'landlordName' },
  },
  {
    id: 'landlord-phone',
    type: 'phone',
    title: 'Landlord phone',
    meta: { fieldName: 'landlordPhone' },
  },
  {
    id: 'avg-rent',
    type: 'text-input',
    title: 'Average rent per room',
    meta: { fieldName: 'avgRent' },
  },
  {
    id: 'under-construction',
    type: 'yes-no',
    title: 'Is the property under construction?',
    meta: { fieldName: 'underConstruction' },
  },
  {
    id: 'construction-stage',
    type: 'dropdown',
    title: 'Stage of construction',
    condition: { field: 'underConstruction', operator: 'eq', value: 'Yes' },
    options: [
      { label: 'Just started (6+ months)', value: 'Just started (6+ months)' },
      { label: 'Lot of work done (3-6 months)', value: 'Lot of work done (3-6 months)' },
      { label: 'Almost done (1-2 months)', value: 'Almost done (1-2 months)' },
    ],
    meta: { fieldName: 'constructionStage' },
  },
  {
    id: 'more-apartments',
    type: 'yes-no',
    title: 'More apartments nearby?',
    meta: { fieldName: 'moreApartments' },
  },
  {
    id: 'family-only',
    type: 'yes-no',
    title: 'Family only?',
    meta: { fieldName: 'familyOnly' },
  },
  {
    id: 'available-when',
    type: 'text-input',
    title: 'When available for rent?',
    meta: { fieldName: 'availableWhen' },
  },
  {
    id: 'exterior-photo',
    type: 'file-upload',
    title: 'Exterior photo',
    fileUpload: { accept: ['image/*'], maxSizeMB: 10, label: 'Exterior photo' },
    meta: { fieldName: 'exteriorPhoto' },
  },
  {
    id: 'other-info',
    type: 'long-text',
    title: 'Other info',
    meta: { fieldName: 'otherInfo' },
  },
];
