import type { FormStep } from '../../schema/types';

export const schema: FormStep[] = [
  {
    id: 'welcome',
    type: 'welcome',
    title: "Let's get you set up.",
    subtitle:
      "We'll collect your details, documents, and bank info so we can manage your home seamlessly.",
    meta: {
      overline: 'Homeowner Onboarding',
      ctaLabel: 'Get Started',
      estimatedTime: '~15 min',
      audience: 'landlord',
      successTitle: "We've got everything we need.",
      successSubtitle: 'Your property specialist will take it from here.',
    },
  },
  {
    id: 'role',
    type: 'single-select',
    title: 'Which best describes you?',
    options: [
      { label: 'I am the owner', value: 'owner' },
      { label: 'I am the point of contact on behalf of the owner', value: 'poc' },
    ],
    meta: { fieldName: 'role' },
  },
  {
    id: 'homeowner-count',
    type: 'dropdown',
    title: 'How many homeowners are there?',
    options: [
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
    ],
    meta: { fieldName: 'homeownerCount' },
  },

  {
    id: 'ho1-info',
    type: 'info-screen',
    title: 'Homeowner 1 — Personal Details',
    subtitle: "We'll need their ID documents and contact info.",
  },
  {
    id: 'ho1-contact',
    type: 'field-group',
    title: 'Contact details',
    fields: [
      { name: 'ho1_firstName', type: 'text', label: 'First name', required: true },
      { name: 'ho1_lastName', type: 'text', label: 'Last name', required: true },
      { name: 'ho1_phone', type: 'tel', label: 'Phone', required: true },
      { name: 'ho1_email', type: 'email', label: 'Email', required: true },
    ],
  },
  {
    id: 'ho1-aadhaar-front',
    type: 'file-upload',
    title: 'Upload Aadhaar card (front)',
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'Aadhaar front' },
    meta: { fieldName: 'ho1_aadhaarFront' },
  },
  {
    id: 'ho1-aadhaar-back',
    type: 'file-upload',
    title: 'Upload Aadhaar card (back)',
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'Aadhaar back' },
    meta: { fieldName: 'ho1_aadhaarBack' },
  },
  {
    id: 'ho1-pan-number',
    type: 'text-input',
    title: 'PAN number',
    meta: { fieldName: 'ho1_panNumber' },
    validation: [
      { type: 'required', message: 'PAN number is required' },
      { type: 'pan', message: 'Enter a valid PAN number' },
    ],
  },
  {
    id: 'ho1-pan-upload',
    type: 'file-upload',
    title: 'Upload PAN card',
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'PAN card' },
    meta: { fieldName: 'ho1_panUpload' },
  },
  {
    id: 'ho1-property-doc',
    type: 'file-upload',
    title: 'Upload property verification document',
    subtitle: 'Sale deed, electricity bill, or tax receipt.',
    fileUpload: {
      accept: ['image/*', 'application/pdf'],
      maxSizeMB: 10,
      label: 'Property verification document',
    },
    meta: { fieldName: 'ho1_propertyDoc' },
  },
  {
    id: 'ho1-bank-info',
    type: 'info-screen',
    title: 'Bank account details for Homeowner 1',
    subtitle: 'We need this to transfer your rental income.',
  },
  {
    id: 'ho1-bank-count',
    type: 'dropdown',
    title: 'How many bank accounts should we set up?',
    options: [
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
      { label: '4', value: '4' },
      { label: '5', value: '5' },
    ],
    meta: { fieldName: 'ho1_bankCount' },
  },
  {
    id: 'ho1-bank-1',
    type: 'field-group',
    title: 'Bank Account 1',
    fields: [
      { name: 'ho1_bank1_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho1_bank1_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho1_bank1_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho1_bank1_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho1-bank-2',
    type: 'field-group',
    title: 'Bank Account 2',
    condition: { field: 'ho1_bankCount', operator: 'gte', value: 2 },
    fields: [
      { name: 'ho1_bank2_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho1_bank2_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho1_bank2_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho1_bank2_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho1-bank-3',
    type: 'field-group',
    title: 'Bank Account 3',
    condition: { field: 'ho1_bankCount', operator: 'gte', value: 3 },
    fields: [
      { name: 'ho1_bank3_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho1_bank3_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho1_bank3_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho1_bank3_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho1-bank-4',
    type: 'field-group',
    title: 'Bank Account 4',
    condition: { field: 'ho1_bankCount', operator: 'gte', value: 4 },
    fields: [
      { name: 'ho1_bank4_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho1_bank4_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho1_bank4_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho1_bank4_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho1-bank-5',
    type: 'field-group',
    title: 'Bank Account 5',
    condition: { field: 'ho1_bankCount', operator: 'gte', value: 5 },
    fields: [
      { name: 'ho1_bank5_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho1_bank5_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho1_bank5_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho1_bank5_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },

  {
    id: 'ho2-info',
    type: 'info-screen',
    title: 'Homeowner 2 — Personal Details',
    subtitle: "We'll need their ID documents and contact info.",
    condition: { field: 'homeownerCount', operator: 'gte', value: 2 },
  },
  {
    id: 'ho2-contact',
    type: 'field-group',
    title: 'Contact details',
    condition: { field: 'homeownerCount', operator: 'gte', value: 2 },
    fields: [
      { name: 'ho2_firstName', type: 'text', label: 'First name', required: true },
      { name: 'ho2_lastName', type: 'text', label: 'Last name', required: true },
      { name: 'ho2_phone', type: 'tel', label: 'Phone', required: true },
      { name: 'ho2_email', type: 'email', label: 'Email', required: true },
    ],
  },
  {
    id: 'ho2-aadhaar-front',
    type: 'file-upload',
    title: 'Upload Aadhaar card (front)',
    condition: { field: 'homeownerCount', operator: 'gte', value: 2 },
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'Aadhaar front' },
    meta: { fieldName: 'ho2_aadhaarFront' },
  },
  {
    id: 'ho2-aadhaar-back',
    type: 'file-upload',
    title: 'Upload Aadhaar card (back)',
    condition: { field: 'homeownerCount', operator: 'gte', value: 2 },
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'Aadhaar back' },
    meta: { fieldName: 'ho2_aadhaarBack' },
  },
  {
    id: 'ho2-pan-number',
    type: 'text-input',
    title: 'PAN number',
    condition: { field: 'homeownerCount', operator: 'gte', value: 2 },
    meta: { fieldName: 'ho2_panNumber' },
    validation: [
      { type: 'required', message: 'PAN number is required' },
      { type: 'pan', message: 'Enter a valid PAN number' },
    ],
  },
  {
    id: 'ho2-pan-upload',
    type: 'file-upload',
    title: 'Upload PAN card',
    condition: { field: 'homeownerCount', operator: 'gte', value: 2 },
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'PAN card' },
    meta: { fieldName: 'ho2_panUpload' },
  },
  {
    id: 'ho2-property-doc',
    type: 'file-upload',
    title: 'Upload property verification document',
    subtitle: 'Sale deed, electricity bill, or tax receipt.',
    condition: { field: 'homeownerCount', operator: 'gte', value: 2 },
    fileUpload: {
      accept: ['image/*', 'application/pdf'],
      maxSizeMB: 10,
      label: 'Property verification document',
    },
    meta: { fieldName: 'ho2_propertyDoc' },
  },
  {
    id: 'ho2-bank-info',
    type: 'info-screen',
    title: 'Bank account details for Homeowner 2',
    subtitle: 'We need this to transfer your rental income.',
    condition: { field: 'homeownerCount', operator: 'gte', value: 2 },
  },
  {
    id: 'ho2-bank-count',
    type: 'dropdown',
    title: 'How many bank accounts should we set up?',
    condition: { field: 'homeownerCount', operator: 'gte', value: 2 },
    options: [
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
      { label: '4', value: '4' },
      { label: '5', value: '5' },
    ],
    meta: { fieldName: 'ho2_bankCount' },
  },
  {
    id: 'ho2-bank-1',
    type: 'field-group',
    title: 'Bank Account 1',
    condition: { field: 'homeownerCount', operator: 'gte', value: 2 },
    fields: [
      { name: 'ho2_bank1_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho2_bank1_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho2_bank1_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho2_bank1_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho2-bank-2',
    type: 'field-group',
    title: 'Bank Account 2',
    condition: { field: 'ho2_bankCount', operator: 'gte', value: 2 },
    fields: [
      { name: 'ho2_bank2_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho2_bank2_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho2_bank2_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho2_bank2_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho2-bank-3',
    type: 'field-group',
    title: 'Bank Account 3',
    condition: { field: 'ho2_bankCount', operator: 'gte', value: 3 },
    fields: [
      { name: 'ho2_bank3_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho2_bank3_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho2_bank3_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho2_bank3_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho2-bank-4',
    type: 'field-group',
    title: 'Bank Account 4',
    condition: { field: 'ho2_bankCount', operator: 'gte', value: 4 },
    fields: [
      { name: 'ho2_bank4_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho2_bank4_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho2_bank4_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho2_bank4_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho2-bank-5',
    type: 'field-group',
    title: 'Bank Account 5',
    condition: { field: 'ho2_bankCount', operator: 'gte', value: 5 },
    fields: [
      { name: 'ho2_bank5_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho2_bank5_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho2_bank5_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho2_bank5_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },

  {
    id: 'ho3-info',
    type: 'info-screen',
    title: 'Homeowner 3 — Personal Details',
    subtitle: "We'll need their ID documents and contact info.",
    condition: { field: 'homeownerCount', operator: 'gte', value: 3 },
  },
  {
    id: 'ho3-contact',
    type: 'field-group',
    title: 'Contact details',
    condition: { field: 'homeownerCount', operator: 'gte', value: 3 },
    fields: [
      { name: 'ho3_firstName', type: 'text', label: 'First name', required: true },
      { name: 'ho3_lastName', type: 'text', label: 'Last name', required: true },
      { name: 'ho3_phone', type: 'tel', label: 'Phone', required: true },
      { name: 'ho3_email', type: 'email', label: 'Email', required: true },
    ],
  },
  {
    id: 'ho3-aadhaar-front',
    type: 'file-upload',
    title: 'Upload Aadhaar card (front)',
    condition: { field: 'homeownerCount', operator: 'gte', value: 3 },
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'Aadhaar front' },
    meta: { fieldName: 'ho3_aadhaarFront' },
  },
  {
    id: 'ho3-aadhaar-back',
    type: 'file-upload',
    title: 'Upload Aadhaar card (back)',
    condition: { field: 'homeownerCount', operator: 'gte', value: 3 },
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'Aadhaar back' },
    meta: { fieldName: 'ho3_aadhaarBack' },
  },
  {
    id: 'ho3-pan-number',
    type: 'text-input',
    title: 'PAN number',
    condition: { field: 'homeownerCount', operator: 'gte', value: 3 },
    meta: { fieldName: 'ho3_panNumber' },
    validation: [
      { type: 'required', message: 'PAN number is required' },
      { type: 'pan', message: 'Enter a valid PAN number' },
    ],
  },
  {
    id: 'ho3-pan-upload',
    type: 'file-upload',
    title: 'Upload PAN card',
    condition: { field: 'homeownerCount', operator: 'gte', value: 3 },
    fileUpload: { accept: ['image/*', 'application/pdf'], maxSizeMB: 10, label: 'PAN card' },
    meta: { fieldName: 'ho3_panUpload' },
  },
  {
    id: 'ho3-property-doc',
    type: 'file-upload',
    title: 'Upload property verification document',
    subtitle: 'Sale deed, electricity bill, or tax receipt.',
    condition: { field: 'homeownerCount', operator: 'gte', value: 3 },
    fileUpload: {
      accept: ['image/*', 'application/pdf'],
      maxSizeMB: 10,
      label: 'Property verification document',
    },
    meta: { fieldName: 'ho3_propertyDoc' },
  },
  {
    id: 'ho3-bank-info',
    type: 'info-screen',
    title: 'Bank account details for Homeowner 3',
    subtitle: 'We need this to transfer your rental income.',
    condition: { field: 'homeownerCount', operator: 'gte', value: 3 },
  },
  {
    id: 'ho3-bank-count',
    type: 'dropdown',
    title: 'How many bank accounts should we set up?',
    condition: { field: 'homeownerCount', operator: 'gte', value: 3 },
    options: [
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
      { label: '4', value: '4' },
      { label: '5', value: '5' },
    ],
    meta: { fieldName: 'ho3_bankCount' },
  },
  {
    id: 'ho3-bank-1',
    type: 'field-group',
    title: 'Bank Account 1',
    condition: { field: 'homeownerCount', operator: 'gte', value: 3 },
    fields: [
      { name: 'ho3_bank1_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho3_bank1_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho3_bank1_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho3_bank1_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho3-bank-2',
    type: 'field-group',
    title: 'Bank Account 2',
    condition: { field: 'ho3_bankCount', operator: 'gte', value: 2 },
    fields: [
      { name: 'ho3_bank2_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho3_bank2_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho3_bank2_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho3_bank2_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho3-bank-3',
    type: 'field-group',
    title: 'Bank Account 3',
    condition: { field: 'ho3_bankCount', operator: 'gte', value: 3 },
    fields: [
      { name: 'ho3_bank3_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho3_bank3_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho3_bank3_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho3_bank3_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho3-bank-4',
    type: 'field-group',
    title: 'Bank Account 4',
    condition: { field: 'ho3_bankCount', operator: 'gte', value: 4 },
    fields: [
      { name: 'ho3_bank4_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho3_bank4_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho3_bank4_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho3_bank4_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },
  {
    id: 'ho3-bank-5',
    type: 'field-group',
    title: 'Bank Account 5',
    condition: { field: 'ho3_bankCount', operator: 'gte', value: 5 },
    fields: [
      { name: 'ho3_bank5_beneficiary', type: 'text', label: 'Beneficiary Name', required: true },
      { name: 'ho3_bank5_accountNumber', type: 'text', label: 'Account Number', required: true },
      { name: 'ho3_bank5_bankName', type: 'text', label: 'Bank Name', required: true },
      { name: 'ho3_bank5_ifsc', type: 'text', label: 'IFSC Code', required: true },
    ],
  },

  {
    id: 'poc-info',
    type: 'info-screen',
    title: 'Point of contact details',
    subtitle: "Who should we reach out to for day-to-day coordination?",
  },
  {
    id: 'poc-contact',
    type: 'field-group',
    title: 'Point of contact',
    fields: [
      { name: 'poc_firstName', type: 'text', label: 'First name', required: true },
      { name: 'poc_lastName', type: 'text', label: 'Last name', required: true },
      { name: 'poc_phone', type: 'tel', label: 'Phone', required: true },
      { name: 'poc_email', type: 'email', label: 'Email', required: true },
    ],
  },
  {
    id: 'alternate-contact',
    type: 'field-group',
    title: 'Alternate contact (optional)',
    fields: [
      { name: 'alt_firstName', type: 'text', label: 'First name' },
      { name: 'alt_lastName', type: 'text', label: 'Last name' },
      { name: 'alt_phone', type: 'tel', label: 'Phone' },
      { name: 'alt_email', type: 'email', label: 'Email' },
    ],
  },
];
